name: Deploy index files

on:
  push:
    branches:
      - source_code # 只在source_code上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  pull_request:
    branches:
      - source_code # 只在source_code上push触发部署
    types: [closed]

jobs:
  index-bulid-job:
    name: Index Bulid Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # 创建token：头像 > Settings > Developer settings > Personal access tokens > Generate new token 权限至少要勾选repo
          # 创建secrets： 源码仓库下 > Settings > Secrets， 创建DEPLOY_TOKEN， 填写刚创建的token，
          repo-token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm i
      - name: Build
        run: |
          npm run docs:build
          cp README.md docs/.vuepress/dist/
          cd docs/.vuepress/dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs/.vuepress/dist/
          CLEAN: true
